language: ruby
rvm:
  - 2.3.1

before_script:
    - cp config/database.yml.travis config/database.yml

script:
    - rails db:create
    - rails db:migrate
    - bundle exec rake test

services:
  - postgresql

addons:
  - postgresql: "9.4"
