language: ruby
rvm:
  - 2.3.1

before_script:

script:
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake test

services:
  - postgresql

addons:
  - postgresql: "9.4"
