<% app_name = "testapp" %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

development:
  <<: *default
  database: <%= "#{app_name}_development" %>

test:
  <<: *default
  database: <%= "#{app_name}_test" %>

production:
  <<: *default
  database: <%= "#{app_name}_production" %>


